server:
  port: 9999

spring:
  datasource:
    druid:
      url: jdbc:mysql:///vhr?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 64801
logging:
  level:
    com.qingqiao.vhr.mapper : debug